services:
  dockup:
    image: borisbrock/dockup:0.0.2
    container_name: dockup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    entrypoint: ["sh", "-c", "while true; do python /app/main.py; sleep 21600; done"]
