version: "3.8"

services:
  image-inspector:
    build: .
    container_name: dockup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    entrypoint: ["sh", "-c", "while true; do python /app/main.py; sleep 21600; done"]
